using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class timecounter : MonoBehaviour
{
    private float T;
    
    void Update()
    {
        T = Time.time;
         if(Input.GetKeyDown(KeyCode.Q))
        {
            Debug.Log("<color=red>0</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.W))
         {
            Debug.Log("<color=red>1</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.E))
         {
            Debug.Log("<color=red>2</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.R))
         {
            Debug.Log("<color=red>3</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.T))
         {
            Debug.Log("<color=red>4</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.Y))
         {
            Debug.Log("<color=red>5</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.U))
         {
            Debug.Log("<color=red>6</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.I))
         {
            Debug.Log("<color=red>7</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.O))
         {
            Debug.Log("<color=red>8</color>");
            Debug.Log(T);
        }
         if(Input.GetKeyDown(KeyCode.P))
         {
            Debug.Log("<color=red>9</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.A)){
            Debug.Log("<color=red>10</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.S)){
            Debug.Log("<color=red>11</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.D)){
            Debug.Log("<color=red>12</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.F)){
            Debug.Log("<color=red>13</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.G)){
            Debug.Log("<color=red>14</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.H)){
            Debug.Log("<color=red>15</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.J)){
            Debug.Log("<color=red>16</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.K)){
            Debug.Log("<color=red>17</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.L)){
            Debug.Log("<color=red>18</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.Z)){
            Debug.Log("<color=red>19</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.X)){
            Debug.Log("<color=red>20</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.C)){
            Debug.Log("<color=red>21</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.V)){
            Debug.Log("<color=red>22</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.B)){
            Debug.Log("<color=red>23</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.N)){
            Debug.Log("<color=red>24</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.M)){
            Debug.Log("<color=red>25</color>");
            Debug.Log(T);
        }
        if(Input.GetKeyDown(KeyCode.Return)){
            Debug.Log("<color=red>26</color>");
            Debug.Log(T);
        }
    }
}
